### ISSUE TITLE
etoolbox error when redefining \author after \maketitle

### ISSUE THREAD

**Issue by soad87** [tud-cd/tudscr#13]
Hi, 

I have a completely fresh MikTex (one user) installation with all updates and the newest TeXnicCenter installed on Windows 7 and 10 systems. When I am running my file I get the error message:

pdflatex> ! Package etoolbox Error: \and undefined.

The error is pointing to the place where the author name is redefined for the confirmation. Surprisingly the output is correct. The \and command is not used since I am the only author of the document. 

Please find attached a short example. I remember not having this error on an older system but cannot find the exact installation parameters to restore the working conditions.

[Diss.txt](https://github.com/tud-cd/tudscr/files/515597/Diss.txt)

**Comment by tudscr** [comment]
Hi,

I'm going to fix this issue. Until then, you can solve your problem by using `\def\and{}` right before `\author{...}`

**Comment by tudscr** [comment]
Fixed with 62e8f4432e6c3e99f9d8f8514aea89ed3486337b
