### ISSUE TITLE
Minimalbeispiel für Abschlussarbeit

### ISSUE THREAD

**Issue by shiaky** [tud-cd/tudscr#15]
Hallo Falk,

hättest du vielleicht Lust ein Minimalbeispiel für eine **Abschlussarbeit** mit gut formatiertem Titelblatt hier zu posten. Deine Dokumentation ist super, aber leider auch super umfangreich und man muss sehr viel über LaTex wissen um sie zu verstehen. Ich denke da an ein wirklich ganz kleines Beispiel in dieser Art hier:

```latex
\documentclass{tudscrartcl}
\usepackage[ngerman]{babel}
\usepackage[utf8x]{inputenc}
\usepackage[T1]{fontenc} 

\title{Titel der Arbeit}
\date{23.09.2015}
\author{Robin}

\begin{document}
\maketitle

\section{Snoop}

\end{document}
```

Vielen vielen Dank!!!!

**Comment by rene-schoene** [comment]
Beispiele und Tutorials sind schon in der Dokumentation, Kapitel 6, enthalten.
Ein Beispiel ähnlich zu deinem ist gleich das erste.
Siehe auch: https://github.com/tud-cd/tudscr/blob/master/source/doc/examples/document.tex

**Comment by shiaky** [comment]
Hallo,

vielen Dank für deine schnelle Antwort. So weit bin ich in den Kapiteln noch gar nicht voran geschritten. Hier ist die Vorlage, die auf meine Bedürfnisse am besten passt:

```latex
\RequirePackage[ngerman=ngerman-x-latest]{hyphsubst}
\documentclass[ngerman,BCOR=4mm]{tudscrreprt}
\usepackage{selinput}\SelectInputMappings{adieresis={ä},germandbls={ß}}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{isodate}
\begin{document}
\faculty{Juristische Fakultät}
\department{Fachrichtung Strafrecht}
\institute{Institut für Kriminologie}
\chair{Lehrstuhl für Kriminalprognose}
\date{18.02.2015}
\title{%
  Entwicklung eines optimalen Verfahrens zur Eroberung des
  Geldspeichers in Entenhausen
}
\subject{master}
\graduation[M.Sc.]{Master of Science}
\author{%
  Mickey Mouse%
  \matriculationnumber{12345678}%
  \dateofbirth{2.1.1990}%
  \placeofbirth{Dresden}%
\and%
  Donald Duck%
  \matriculationnumber{87654321}%
  \dateofbirth{1.2.1990}%
  \placeofbirth{Berlin}%
}
\matriculationyear{2010}
\supervisor{Dagobert Duck \and Mac Moneysac}
\professor{Prof. Dr. Kater Karlo}
\maketitle
\end{document}
```

**Comment by tudscr** [comment]
Hallo @shiaky,

wie @rene-schoene schon erwähnt hat sind allerlei Beispiele sowohl im Handbuch als auch hier in diesem GitHub-Repository ([Klick](https://github.com/tud-cd/tudscr/tree/master/source/doc/examples)) oder lokal auf deinem Rechner im Pfad deiner LaTeX-Distribution unter <texpath>/source/latex/tudscr/doc/examples zu finden. Für Fragen speziell zum Anfertigen von Abschlussarbeiten kannst du dir außerdem das Tutorial "treatise" mal ansehen (Link im Handbuch oder über die Konsole `texdoc treatise` eingeben).

Tatsächlich ist die Doku etwas umfangreicher, als dies von mir zu Beginn der Entwicklung geplant war. Aber nicht umsonst gibt's ein Vorwort, im ersten Kapitel den Abschnitt "Schnelleinstieg" und ein Inhaltsverzeichnis, welches meiner Meinung nach durchaus aussagekräftig ist. 

Das im Handbuch Grundkenntnisse von LaTeX vorausgesetzt werden, steht ja auch so geschrieben -- ergänzt um Hinweise, wo man für die allerersten Gehversuche mit LaTeX Hilfe bekommt. Ich habe auch schlichtweg keine Zeit und Muße, ein weiteres LaTeX-Einsteiger-Tutorial zu schreiben, davon gibt es schon einige, wenn auch nur wenige gute. 

In der Konsequenz halte ich auch nicht für sinnvoll, gleich zu Beginn des Handbuchs mit einem Beispiel einzusteigen, weil dies im Zweifel den unerfahrenen Anwender trotzdem per Copy&Paste loszulegen, ohne zu wissen, was er tatsächlich tut. Es gibt nichts schlimmeres, als von irgendwoher erhaltene oder aus irgendeinem Forum kopierte "LaTeX-Vorlagen". Die sind meistens mit unzähligen Paketen gefüllt, die teilweise veraltet, doppelt oder unnötig sind oder schlimmer noch Inkompatibilitäten erzeugen. Man sollte schon genau wissen, welche Pakete eingebunden werden und warum. Siehe dazu auch http://www.komascript.de/latexvorlage

Grüße
