### ISSUE TITLE
Abstract nicht im Inhaltsverzeichnis aufführen

### ISSUE THREAD

**Issue by shiaky** [tud-cd/tudscr#16]
Hallo Falk,

erst einmal vielen vielen Dank für deine wahnsinnig aufwendige TU-Klasse und die überaus ausführliche Doku. Entschuldige meine ganzen dummen Fragen, aber ich finde wo anders keine Lösung.

Ich habe den Abstract wie bei dir dokumentiert über
```
\TUDoption{abstract}{section,multiple}
\begin{abstract}[pagestyle=empty.tudheadings]
...
\nextabstract[english]
...
\end{abstract}
```
gebaut. Leider werden dann im Inhaltsverzeichnis die beiden Punkte `Zusammenfassung` und `Abstract` angezeigt. Das möchte ich gern vermeiden. Gibt es dafür eine Möglichkeit.

Vielen Dank dir,
Robin

**Comment by tudscr** [comment]
Hallo Robin,

zunächst einmal der Hinweis, was du tun solltest um schnell und problemlos Hilfe zu bekommen: http://komascript.de/vermeidbarefehler und http://komascript.de/minimalbeispiel

Dokumentation zur aktuellen Version v2.05f S. 44: abstract=notoc

**Comment by shiaky** [comment]
Vielen Dank :D
