### ISSUE TITLE
Titelblatt: Silbentrennung bei Autoren vermeiden

### ISSUE THREAD

**Issue by shiaky** [tud-cd/tudscr#17]
Hallo Falk,

erst einmal vielen vielen Dank für deine wahnsinnig aufwendige TU-Klasse und die überaus ausführliche Doku. Entschuldige meine ganzen dummen Fragen, aber ich finde wo anders keine Lösung.

Wir müssen ein Paper mit 14 AutorInnen erstellen, die alle auf dem Titelblatt aufgeführt werden müssen. Für die `author` Umgebung habe ich die Lösung gefunden, statt `\and` ein ` ,` zu verwenden. Leider führt Latex aber  innerhalb des Autorenfeldes Silbentrennung durch, so dass die AutorInnennamen sehr ungünstig getrennt werden. 

```
\author{%
   Max Muster%
   , %
   Max Muster%
   , %
   Max Muster%
   , %
   Max Muster%
   , %
   Max Muster%
   , %
   Max Muster%
   , %
   Max Muster%
   , %
   Max Muster%
   , %
   Max Muster%
   , %
   Max Muster%
   , %
   Max Muster%
   , %
   Max Muster%
   , %
   Max Muster%
   , %
   Max Muster%
   , %
   Max Muster%
}
```

Gibt es vielleicht eine Möglichkeit, Silbentrennung für die Autoren-Umgebung zu unterdrücken.

LG
Robin

**Comment by tudscr** [comment]
Hallo Robin,

zunächst einmal der Hinweis, was du tun solltest um schnell und problemlos Hilfe zu bekommen: http://komascript.de/vermeidbarefehler und http://komascript.de/minimalbeispiel

Selbst, wenn ich deinen Code-Schnipsel in ein Minimalbeispiel packe, sehe ich dein Problem nicht. Deswegen der simple und ungetestete Hinweis: `\mbox{Max Muster}`

**Comment by shiaky** [comment]
Entschuldige, ich bin noch neu in der Latex-Welt. Hier in ein Minimalbeispiel, dass das Problem verdeutlichen sollte:

```
\RequirePackage[ngerman=ngerman-x-latest]{hyphsubst}
\documentclass[english,ngerman,BCOR=6mm,cdgeometry=no,DIV=13,abstract=notoc]{tudscrreprt}
\usepackage{selinput}\SelectInputMappings{adieresis={ä},germandbls={ß}}
\usepackage[T1]{fontenc}
\usepackage{babel}
%%% schönes Datum
\usepackage{isodate}
\begin{document}
%%% Titelseite 
\faculty{Fakultät Informatik}
\institute{Institut für Historische Denkweisen}
\chair{Professur bunte bunte Knete}
\date{01.01.2017}
\title{%
Ein langer Titel der hier nicht weiter von Bedeutung ist}
\subject{research}
\author{%
   Anakin Skywalker%
   , %
   Qui-Gon Jinn%
   , %
   Darth Sidious%
   , %
   Shmi Khayretdinov%
   , %
   Wilhuff Tarkin%
   , %
   Lando Calrissian%
   , %
   Bill Bailey%  
   , %
   Anna Chancellorertzkiv%
   , %
   Radzhiv Skywalker%
   , %
   Zooey Deschanel%
   , %
   Warwick Davis%
   , %
   Martin Freeman%
   , %
   Richard Griffiths%
   , %
   Kelly Macdonald%
   , %
   John Malkovich%
   , %
   Lynn Robertson Bruce%
}
\supervisor{Dr.-Ing. Muster Muster}
\maketitle
\end{document}

```
Es werden Umbrüche in den Namen vorgenommen. Im Original auch so ungünstige Sachen wie `Mar-tin Mustermann`.


Mit `\mbox{*}` sieht das ganze dann so aus:
```
\RequirePackage[ngerman=ngerman-x-latest]{hyphsubst}
\documentclass[english,ngerman,BCOR=6mm,cdgeometry=no,DIV=13,abstract=notoc]{tudscrreprt}
\usepackage{selinput}\SelectInputMappings{adieresis={ä},germandbls={ß}}
\usepackage[T1]{fontenc}
\usepackage{babel}
%%% schönes Datum
\usepackage{isodate}
\begin{document}
%%% Titelseite 
\faculty{Fakultät Informatik}
\institute{Institut für Historische Denkweisen}
\chair{Professur bunte bunte Knete}
\date{01.01.2017}
\title{%
Ein langer Titel der hier nicht weiter von Bedeutung ist}
\subject{research}
\author{%
   \mbox{Anakin Skywalkerinani}%
   , %
   \mbox{Qui-Gon Jinndohuse}%
   , %
   \mbox{Darth Sid}%
   , %
   \mbox{Shmi Khayretdinov}%
   , %
   \mbox{Wilhuff Tarkin}%
   , %
   \mbox{Lando Calrissian}%
   , %
   \mbox{Bill Bailey}%  
   , %
   \mbox{Anna Chancellorertzkiv}%
   , %
   \mbox{Radzhiv Skywalker}%
   , %
   \mbox{Zooey Deschanel}%
   , %
   \mbox{Warwick Davis}%
   , %
   \mbox{Martin Freeman}%
   , %
   \mbox{Richard Griffiths}%
   , %
   \mbox{Kelly Macdonald}%
   , %
   \mbox{John Malkovich}%
   , %
   \mbox{Lynn Robertson Bruce}%
}
\supervisor{Dr.-Ing. Muster Muster}
\maketitle
\end{document}
```

Die Namen sind hier etwas angepasst um dem `\mbox{*}` Bild des Originals eher zu entsprechen.

Hast du eine Idee, wie man das optimieren kann?

**Comment by tudscr** [comment]
Und schon wird dein Problem greifbar. Es liegt schlichtweg daran, dass ich anscheinend vergessen habe, in der Klasse standardmäßig den linksbündigen Flattersatz auf der Titelseite zu aktivieren. Das wird für die nächste Version nachgeholt. Dir kann folgendermaßen geholfen werden:
```tex
\RequirePackage[ngerman=ngerman-x-latest]{hyphsubst}
\documentclass[english,ngerman,BCOR=6mm,cdgeometry=no,DIV=13,abstract=notoc]{tudscrreprt}
\usepackage{selinput}\SelectInputMappings{adieresis={ä},germandbls={ß}}
\usepackage[T1]{fontenc}
\usepackage{babel}
%%% schönes Datum
\usepackage{isodate}
\begin{document}
%%% Titelseite 
\faculty{Fakultät Informatik}
\institute{Institut für Historische Denkweisen}
\chair{Professur bunte bunte Knete}
\date{01.01.2017}
\title{%
Ein langer Titel der hier nicht weiter von Bedeutung ist}
\subject{research}
\addtokomafont{titlepage}{\raggedright}
\author{%
   Anakin~Skywalkerinani, 
   Qui"~Gon~Jinndohuse, 
   Darth~Sid, 
   Shmi~Khayretdinov, 
   Wilhuff~Tarkin, 
   Lando~Calrissian, 
   Bill~Bailey, 
   Anna~Chancellorertzkiv,
   Radzhiv~Skywalker, 
   Zooey~Deschanel, 
   Warwick~Davis, 
   Martin~Freeman, 
   Richard~Griffiths, 
   Kelly~Macdonald,
   John~Malkovich,
   Lynn~Robertson~Bruce
}
\supervisor{Dr.-Ing. Muster Muster}
\maketitle
\end{document}
```
Ich weiß auch nicht so recht, warum du so umständlich die Kommas zwischen den einzelnen Autoren setzt. Also `\addtokomafont{titlepage}{\raggedright}` aktiviert den Flattersatz, damit bist du schon mal die Silbentrennung los. Und die Verwendung von `~` erzeugt ein geschütztes Leerzeichen, an welchem kein Zeilenumbruch erzeugt wird. Fertig.

**Comment by shiaky** [comment]
Danke Falk, du bist mein Held. Wie schaffst du das nur immer so zeitnah zu antworten. Ich hoffe die TU zahlt für diesen Service.

Das mit dem komplizierten Kommas kommt noch aus der Zeit in der ich versucht habe das mit \and` umzusetzen. Das hatte ich schlicht so beibehalten. Ich habe es jetzt aber aufgeräumt. Jetzt weiß ich ja, dass deine Lösung super funktioniert. 

Vielen Dank nochmal!!!

**Comment by tudscr** [comment]
Mit vernünftigen MB ist das meistens ein Aufwand von wenigen Minuten, bezahlt werde ich dafür aber nicht ;)

**Comment by shiaky** [comment]
Frechheit...schließlich kommt das der TU zu Gute eine CD Latex Klasse zu haben.

Dann noch mehr Dank dir!
