### ISSUE TITLE
Font install script: tftopl: command not found (Windows, TeXLive)

### ISSUE THREAD

**Issue by roidanton** [tud-cd/tudscr#2]
tftopl is not found in Windows 8.1, TeXLive 2014 (batch section 00/19 - 18/19). Using font install from release v2.03. 

[tftopl is reported as a unix command](http://www.linuxcommand.org/man_pages/tftopl1.html), so it is likely part of TeXLive/MikTeX. With the MikTex installation on another system this error did not occur.

So in [Adding tftopl to TeXLive Basic](http://tex.stackexchange.com/questions/203570/adding-tftopl-pltotf-to-texlive-basic) the binary is listed. However in my local TeXlive installation there is no *tftopl.exe* in `texlive/2014/bin/win32/` or elsewhere in the texlive folder, though the TeXLive Manager lists *tftopl* as installed with packet *texware*.

Perhaps the problem is related to the TeXLive basic/custom installation profile.

**Comment by roidanton** [comment]
The [answer above](http://tex.stackexchange.com/questions/203570/adding-tftopl-pltotf-to-texlive-basic) provided the solution: When using TeXLive, the packet *fontware* has to be installed. Problem solved!

This should be added to the tudscr documentation so I leave this issue opened.

**Comment by tudscr** [comment]
hint to tudscr-manual v2.04 added
