### ISSUE TITLE
Problem mit "lunl8r.map"

### ISSUE THREAD

**Issue by funjetfan** [tud-cd/tudscr#20]
Ich habe Debian 8.0 mit TeXLive installiert und möchte nun die Schriftarten installieren, was unter Ubuntu schon mal erfolgreich funktioniert.

Das Problem führt auch dazu, dass man die documentclass tudscrreprt nicht mehr verwenden kann, dort scheitert es ebenfalls an lunl8r.

Das ist der Inhalt von missfont.log:

> mktexpk --mfmode / --bdpi 600 --mag 0+480/600 --dpi 480 lunlo8r
mktexpk --mfmode / --bdpi 600 --mag 0+480/600 --dpi 480 lunlo8r
mktexpk --mfmode / --bdpi 600 --mag 0+480/600 --dpi 480 lunlo8r
mktexpk --mfmode / --bdpi 600 --mag 0+480/600 --dpi 480 lunlo8r
mktexpk --mfmode / --bdpi 600 --mag 0+480/600 --dpi 480 lunlo8r
mktexpk --mfmode / --bdpi 600 --mag 0+480/600 --dpi 480 lunlo8r
mktexpk --mfmode / --bdpi 600 --mag 0+480/600 --dpi 480 lunlo8r
mktexpk --mfmode / --bdpi 600 --mag 0+480/600 --dpi 480 lunlo8r
mktexpk --mfmode / --bdpi 600 --mag 0+480/600 --dpi 480 lunlo8r
mktexpk --mfmode / --bdpi 600 --mag 0+480/600 --dpi 480 lunlo8r
mktexpk --mfmode / --bdpi 600 --mag 0+480/600 --dpi 480 lunlo8r
mktexpk --mfmode / --bdpi 600 --mag 0+480/600 --dpi 480 lunlo8r
mktexpk --mfmode / --bdpi 600 --mag 0+480/600 --dpi 480 lunlo8r
mktexpk --mfmode / --bdpi 600 --mag 0+480/600 --dpi 480 lunlo8r
mktexpk --mfmode / --bdpi 600 --mag 0+480/600 --dpi 480 lunlo8r
mktexpk --mfmode / --bdpi 600 --mag 0+540/600 --dpi 540 lunl8r
mktexpk --mfmode / --bdpi 600 --mag 0+540/600 --dpi 540 lunl8r
mktexpk --mfmode / --bdpi 600 --mag 0+540/600 --dpi 540 lunl8r
mktexpk --mfmode / --bdpi 600 --mag 0+540/600 --dpi 540 lunl8r
mktexpk --mfmode / --bdpi 600 --mag 0+540/600 --dpi 540 lunl8r
mktexpk --mfmode / --bdpi 600 --mag 0+540/600 --dpi 540 lunl8r
mktexpk --mfmode / --bdpi 600 --mag 0+540/600 --dpi 540 lunl8r
mktexpk --mfmode / --bdpi 600 --mag 0+540/600 --dpi 540 lunl8r
mktexpk --mfmode / --bdpi 600 --mag 0+540/600 --dpi 540 lunl8r

Und das ist die Ausgabe beim Aufruf von updmap:

> =====================================================================
Aufruf von 'updmap'
=====================================================================
updmap is using the following updmap.cfg files (in precedence order):
  /home/peter/.texmf-config/web2c/updmap.cfg
  /etc/texmf/web2c/updmap.cfg
  /usr/share/texmf/web2c/updmap.cfg
  /usr/share/texlive/texmf-dist/web2c/updmap.cfg
updmap is using the following updmap.cfg file for writing changes:
  /home/peter/.texmf-config/web2c/updmap.cfg
dvips output dir: "/home/USER/.texmf-var/fonts/map/dvips/updmap"
pdftex output dir: "/home/USER/.texmf-var/fonts/map/pdftex/updmap"
dvipdfmx output dir: "/home/USER/.texmf-var/fonts/map/dvipdfmx/updmap"
updmap [ERROR]: The following map file(s) couldn't be found:
updmap [ERROR]: 	lunl8r.map (in /home/peter/.texmf-config/web2c/updmap.cfg)
updmap [ERROR]: Did you run mktexlsr?

	You can disable non-existent map entries using the option
	  --syncwithtrees.

Bislang habe ich noch keine erfolgreichen Lösungen gefunden. Und - da ich eben das Problem bei MacTex gesehen habe - ich verwende die richtigen Dateien "Univers_PS.zip" und "DIN_Bd_ps.zip", nur musse bei letzterem "ps" groß geschrieben werden ("PS")

**Comment by mrpiggi** [comment]
Wenn ich dir helfen soll, dann brauch ich ein log-File der Schriftinstallation. Steht auch so unter 1.2.3 in der Doku. Ruf mal im Terminal

    bash tudscr_fonts_install.sh > tudscr_fonts_install.log

auf und schicke mir das Log-File entweder als E-Mail oder poste es direkt hier.

**Comment by mrpiggi** [comment]
Crosspost unter http://latex.wcms-file3.tu-dresden.de/phpBB3/viewtopic.php?f=11&t=461&p=1606#p1606
