### ISSUE TITLE
beamerthemeTUD

### ISSUE THREAD

**Issue by francesco-kriegel** [tud-cd/tudscr#21]
Hiermit möchte ich auf mein Repository [https://github.com/francesco-kriegel/beamerthemeTUD](https://github.com/francesco-kriegel/beamerthemeTUD) aufmerksam machen, welches eine Präsentationsvorlage für LaTeX im Corporate Design der TU Dresden beinhaltet.  Bei Interesse kann dieses gern übernommen und auch verändert werden.

**Comment by mrpiggi** [comment]
Hallo,
ich habe mir die Dateien angesehen und bin gleich über einiges gestolpert. Als erstes ist mir die Definition für Farben und Schriften aufgefallen. Dafür gibt es seit geraumer Zeit im TUD-Script-Bundle die passenden Pakete `tudscrfonts` und `tudscrcolor`. Des weiteren gibt es unter https://github.com/tud-cd/tud-cd ja bereits einen beamer-Style, mir ist nicht ganz klar, worin jetzt der große Unterschied besteht bzw. Vorteile liegen sollen.

**Comment by mrpiggi** [comment]
Keine Reaktion ist auch eine

**Comment by francesco-kriegel** [comment]
Bitte entschuldigen Sie die späte Antwort.

Also: ich kannte das genannte beamertheme nicht, daher auch mein obiger Kommentar bzw. informeller pull request.  Wenn es schon ein beamertheme gibt, dann ist ja alles in Ordnung.  Ich habe mir das noch nicht genauer angeschaut, und kann daher auch nicht sagen, worin sich beide unterscheiden.  Ich hatte einfach mal eine Vorlage, die an meinem Institut häufig verwendet wird, angepasst und das Resultat in das genannte Repository hochgeladen.

**Comment by mrpiggi** [comment]
Hallo,

was das Thema Vorlage anbelangt, kann ich nur auf den Beitrag von Markus Kohm verweisen: https://komascript.de/latexvorlage

Das Thema beamer-Style steht bei mir schon eine ganze Weile auf der ToDo-Liste, leider bin ich bisher noch nicht dazu gekommen. Die von dir bereitgestellten Dateien kann ich leider nicht einfach so übernehmen, da stößt mir einiges auf. Zum einen ist nichts dokumentiert, weder der Quelltext selbst noch für den Anwender. 

Die beiden Dateien `beamercolorthemeTUD.sty` und ´beamerfontthemeTUD.sty´ sollten auf ´tudscrcolor.sty´ respektive ´tudscrfonts.sty´ bauen. `beamerouterthemeTUDminiframes.sty` sieht ziemlich abgekupfert aus. Das ist prinzipiell nicht schlimm, aber wenn dann noch das vorherige Copyright auftaucht und jede Menge auskommentiert ist, dann erweckt das kein großes Vertrauen. Die Angabe von Institut etc. in `beamerouterthemeTUDtitlepage.sty` schmeckt mir auch nicht, da habe ich in meinen Klassen eine wesentlich elegantere und vor allem robustere Lösung gefunden.

Das ist auch nicht böse gemeint. Wenn du mit dem beamer-Stil so arbeiten kannst, ist ja alles gut. Aber ich werde das so definitiv nicht auf einen Anwender loslassen, insbesondere weil ich schon versuche, alles halbwegs verständlich für LaTeX-Einsteiger zu gestalten.

Grüße
Falk

**Comment by francesco-kriegel** [comment]
Lieber Falk,

ich bin nicht darauf erpicht, dass die Vorlage unbedingt übernommen wird -- wie gesagt war das nur ein Vorschlag.  Wenn der Code zu unübersichtlich ist, könnte ich den mal aufräumen, wenn überschüssige Zeit vorhanden ist.

Grundsätzlich ist der Quelltext eine Mischung aus dem originalen miniframes-Thema, der oft verwendeten LaTeX-Vorlage an unserem Institut, und manchen Anpassungen (teilweise von Stack Exchange, teilweise eigene).  Insbesondere die Anpassung, dass die Navigationskreise neben den Abschnittsnamen in der Kopfzeile erscheinen, stammt von [http://tex.stackexchange.com/questions/88182/beamer-miniframes-side-by-side-section-names-and-navigation-dots](http://tex.stackexchange.com/questions/88182/beamer-miniframes-side-by-side-section-names-and-navigation-dots), und die Anpassung, dass Navigationskreise auch ohne Unterabschnitte angezeigt werden stammt von [http://tex.stackexchange.com/questions/2072/beamer-navigation-circles-without-subsections](http://tex.stackexchange.com/questions/2072/beamer-navigation-circles-without-subsections).  Der Rest ist entweder aus dem originalen miniframes-Thema, aus der Beamer-Vorlage unseres Instituts, oder von mir angepasst worden.  Die auskommentierten Zeilen stammen noch von Experimenten und können daher getrost ignoriert oder entfernt werden.

Also, wenn ich mal Zeit finde, werde ich den Quellcode aufräumen, ein ansprechendes Minimalbeispiel schreiben, und Deine Hinweise beachten.  Bis dahin heißt es erstmal: works for me.

Beste Grüße
Francesco

**Comment by keinstein** [comment]
Hallo @francesco-kriegel ,
ich bin leider immer noch nicht dazu gekommen, Deine Folien auszuprobieren. Ich würde vorschlagen, Du baust das was Deiner Meinung nach noch fehlt in https://github.com/tud-cd/tud-cd ein und Du, @mrpiggi meckerst, was Dir an den Patches nicht passt, bzw. was Deiner Meinung nach am Beamerstil umgestellt werden muss. Ich glaube nicht, dass es sinnvoll ist, an jedem Institut einen eigenen Beamer-Stil zu pflegen, der genau das nicht leistet, was der eigentliche Sinn eines CD entspricht, nämlich einprägsam und leicht wieder zu erkennen zu sein.

Wenn wir uns zusammentun, können wir auch mit den Leuten vom Unimarketing über die Dinge reden, die sich mit Beamer besser bewerkstelligen lassen, als mit PowerPoint. Da das CD-Handbuch sich dazu ausschweigt, habe ich auch kein Problem damit, entsprechende Dinge nachzurüsten, sofern sie sich optional zuschalten und CD-konform umsetzen lassen. Zum Beispiel definiert, das CD, dass im TUD-Seitenkopf außer dem TUD-Logo und möglicherweise einem Dresden-Concept-Logo nichts zu suchen hat. Trotzdem gibt es eine Funktion, mit der man ein zweites Logo hinzufügen kann, da sich das in einem gemeinsam vorbereiteten Vortrag zu einem Kooperationsprojekt manchmal nicht vermeiden lässt. Allerdings ist dies nicht der Standardwert.

Viele Grüße

Tobias.

P.S.: Wenn Du mehrere Einzelpatches machst, räumt sich der Code auch von alleine etwas auf.
