### ISSUE TITLE
pdflatex hängt bei Abkürzung in section-Titel bei Nutzung der Pakete acronym und hyperref

### ISSUE THREAD

**Issue by sfo** [tud-cd/tudscr#23]
Bei Benutzung des Paketes `acronym` in Verbindung mit `hyperref` und Abkürzungen in Überschriften (section, subsection, etc.) läuft der Übersetzungsprozess an dieser Stelle ohne weitere Ausgabe unendlich lang weiter. Mit `Strg+C Strg+D` kann er abgebrochen werden und es erscheint diese Fehlermeldung:

```
^C! Interruption.
\sl@StoreMessage ...oveGobbletwo #1\sl@Terminator 
                                                  \@gobbletwo \sl@Terminator...
l.7     \section{\acl{HW}}
                          
? 
! Emergency stop.
\sl@StoreMessage ...oveGobbletwo #1\sl@Terminator 
                                                  \@gobbletwo \sl@Terminator...
l.7     \section{\acl{HW}}
                          
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on mwe.log.
```

Das Problem tritt auch bei `tudscrartcl` und `tudscrreprt` auf. Bei Nutzung der Standard-Klassen (`scrbook, scrartcl, srcreprt`) tritt das Problem nicht auf, die Übersetzung läuft normal durch. Die Reihenfolge der Einbindung ist auch egal.

Folgendes MWE verdeutlicht den Sachverhalt:

```LaTeX
\documentclass{tudscrbook}

\usepackage{acronym}
\usepackage{hyperref}

\begin{document}
    \section{\acl{HW}}                                                                                                                                                                                        
        \ac{HW}

    \section{List of Abbrevations}
        \begin{acronym}
            \acro{HW}{Hello, World!}
        \end{acronym}
\end{document}
```

Umgebung (auch zu finden als docker-image: https://hub.docker.com/r/ksfo/texlive/):
* TexLive 2017 full
* pdflatex: pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017)
* tudscr: cat-version: 2.05m, revision: 44480
* hyperref: cat-version: 6.85a, revision: 43547
* acronym: cat-version: 1.41, revision: 36582

**Comment by mrpiggi** [comment]
Das Problem liegt darin begründet, dass bei der Verwendung des CD-Layouts die Überschriften automatisch in Majuskeln/Großbuchstaben gesetzt werden und dafür das Argument der Gliederungsbefehle expandiert werden muss. Da der Befehl `\acl{...}` nicht expandierbar ist, kommt es folglich zum beschriebenen Fehler. Eine Möglichkeit ist, dass Expandieren manuell zu unterbinden.

    \documentclass{tudscrbook}
    \usepackage[T1]{fontenc}
    \usepackage{selinput}
    \SelectInputMappings{adieresis={ä},germandbls={ß}}
    
    \usepackage{acronym}
    \usepackage{hyperref}
    
    \begin{document}
    
    \tableofcontents
    
    \section{\unexpanded{\acl{HW}}}
    \ac{HW}
    
    \section{List of Abbrevations}
    \begin{acronym}
      \acro{HW}{Hello, World!}
    \end{acronym}
    \end{document}

Dabei wird allerdings die Überschrift auch nicht mehr in Majuskeln/Großbuchstaben formatiert. Auch der Eintrag des PDF-Lesezeichens enthält lediglich das Label. Eine mögliche Lösung wäre es, von `acronym` auf `glossaries` zu wechseln, welches **nach** `hyperref` geladen werden muss. Dieses bietet neben den gewohnten Befehlen für Abkürzungen (`\ac...` über die Paketoption `shortcut`) auch solche an, welche einzelne Felder einer definierten Abkürzung expandieren können. [Das Ergebnis im PDF (klick).](https://github.com/tud-cd/tudscr/files/1081062/acc-test.pdf)

    \documentclass{tudscrbook}
    \usepackage[T1]{fontenc}
    \usepackage{selinput}
    \SelectInputMappings{adieresis={ä},germandbls={ß}}
    
    \usepackage{hyperref}
    \usepackage[%
      nomain,acronym,shortcuts,
      section=section,toc
    ]{glossaries}
    \makeglossaries
    
    \begin{document}
    \newacronym{HW}{HW}{Hello, World!}
    
    \tableofcontents
    
    \section{\glsentrydesc{HW}}
    \ac{HW} vs \acl{HW}
    
    \printacronyms
    \printacronyms[title={List of Abbrevations}]
    \end{document}

Der Umstieg auf `glossaries` hätte auch den Vorteil, dass du eine einzige Liste aller Abkürzungen zentral pflegen und diese in jedem Dokument mit `\input{...}` (nach `\begin{document}` um Probleme mit der Eingabekodierung zu vermeiden) einbinden könntest. Dabei werden die Einträge automatisch sortiert. Um das Abkürzungsverzeichnis zu erstellen, musst du ` makeglossaries.exe <Dateiname>` aufrufen.

Generell ist die Geschichte mit den Überschriften eine leidige. Ich werde auch versuchen, in der Version v2.06 eine Benutzerschnittstelle zu implementieren, um mit den daraus resultierenden Problemen besser und einfacher umgehen zu können. Aber wann ich das in Angriff nehmen kann, steht in den Sternen. Große Hoffnungen will ich nicht machen...

Grüße
Falk

**Comment by sfo** [comment]
> Da der Befehl \acl{...} nicht expandierbar ist, kommt es folglich zum beschriebenen Fehler.

Das finde ich merkwürdig, denn sobald das Paket `hyperref` weg gelassen wird, funktioniert die PDF-Erzeugung problemlos. Hier scheint ein tieferer Zusammenhang schuld zu sein.

Ein `\unexpanded` hilft aber tatsächlich (inkl. des genannten Nachteils) und `glossaries` werde ich mir auch einmal anschauen.
