### ISSUE TITLE
E-Mail Adresse in author Umgebung

### ISSUE THREAD

**Issue by shiaky** [tud-cd/tudscr#24]
Hallo Falk,

ist es möglich, seine E-Mail Adresse  in der `author` Umgebung des Titelblattes anzugeben?

Folgendes...

```latex
\RequirePackage[ngerman=ngerman-x-latest]{hyphsubst}
\documentclass[english,ngerman,BCOR=6mm,cdgeometry=no,DIV=13,abstract=notoc]{tudscrreprt}
\usepackage{selinput}\SelectInputMappings{adieresis={ä},germandbls={ß}}
\usepackage[T1]{fontenc}
\usepackage{babel}
%%% schönes Datum
\usepackage{isodate}
\begin{document}
%%% Titelseite 
\faculty{Fakultät Informatik}
\institute{Institut für Historische Denkweisen}
\chair{Professur bunte bunte Knete}
\date{01.01.2017}
\title{%
Ein langer Titel der hier nicht weiter von Bedeutung ist}
\subject{research}
\author{%
   Max Mustermann%
   \emailaddress{max.mustermann@tu-dresden.de}%
   \matriculationnumber{12 34 567}%
   \dateofbirth{01.01.1900}%
   \placeofbirth{Dresden}%
}
\supervisor{Dr.-Ing. Muster Muster}
\maketitle
\end{document}
```

scheint leider nicht zu funktionieren :/

Danke dir !

LG
Robin

**Comment by mrpiggi** [comment]
Hallo Robin,
das liegt schlicht und ergreifend daran, dass `\emailaddress` für die drei Hauptklassen erstens ohnehin nicht  definiert ist und zweitens selbst wenn so wäre, der angegebene Inhalt gar nicht von `\author`´ausgewertet werden würde. Ich habe mir das mal vorgemerkt, allerdings werde ich deswegen nicht gleich eine neue Version zum Release fertig machen. Das kommt dann irgendwann mit einem späteren Bugfix oder in ferner Zeit in der Version v2.06

Bis dahin kannst du dir damit helfen, dass du die E-Mail-Adresse einfach mit `\authormore{max.mustermann@tu-dresden.de}` angibst. Willst du einen klickbare Link erzeugen, ginge dies folgendermaßen:

    \RequirePackage[ngerman=ngerman-x-latest]{hyphsubst}
    \documentclass[english,ngerman,BCOR=6mm,cdgeometry=no,DIV=13,abstract=notoc]{tudscrreprt}
    \usepackage[T1]{fontenc}
    \usepackage{selinput}\SelectInputMappings{adieresis={ä},germandbls={ß}}
    \usepackage{babel}
    %%% schönes Datum
    \usepackage{isodate}
    \usepackage{hyperref}
    \begin{document}
    %%% Titelseite 
    \faculty{Fakultät Informatik}
    \institute{Institut für Historische Denkweisen}
    \chair{Professur bunte bunte Knete}
    \date{01.01.2017}
    \title{%
    Ein langer Titel der hier nicht weiter von Bedeutung ist}
    \subject{research}
    \newrobustcmd*\myemailaddress[1]{%
      \begingroup
        \urlstyle{same}%
        \href{mailto:#1}{\nolinkurl{#1}}%
      \endgroup
    }
    \author{%
       Max Mustermann%
       \authormore{\myemailaddress{max.mustermann@tu-dresden.de}}
       \matriculationnumber{12 34 567}%
       \dateofbirth{01.01.1900}%
       \placeofbirth{Dresden}%
    }
    \supervisor{Dr.-Ing. Muster Muster}
    \maketitle
    \end{document}

**Comment by shiaky** [comment]
Perfekt, vielen Dank dir :D :smiley_cat:
