### ISSUE TITLE
Skript zur Schriftinstallation funktioniert nicht unter Lubuntu 16.04

### ISSUE THREAD

**Issue by steindev** [tud-cd/tudscr#25]
Auf meinem standard Lubuntu 16.04 funktioniert das Skript zur Schrifteninstallation nicht. Der Ordner indem sich die tex binaries befinden wird nicht korrekt von `symlinkpath = $(which tex)` auf `texpath` weitergegeben.

Bei mir ist Tex auf der lokalen Festplatte installiert,  `$(which tex) = /opt/texlive/2017/bin/x86_64-linux/tex`.

Bei der Ausführung des Schrifteninstallationsskripts wird `texpath` allerdings auf den Ordner gesetzt, indem ich das Skript gerade ausführe. In meinem Fall war das der `Downloads`-Ordner in `HOME`. Dementsprechend erhielt ich die Meldung, dass meine Tex-Installation in `Downloads` gefunden wurde. Daran schlossen sich Fehlermeldungen über die nichtgefundenden aber benötigten Pakete an.

Nachdem ich im Skript den Pfad auf die Tex-Installation manuell gesetzt gesetzt habe, `texpath="/opt/texlive/2017/bin/x86_64-linux"`, verlief die Installation der Schriften problemlos.

**Comment by mrpiggi** [comment]
Hi,
leider kann ich nicht für jedes unixartige Betriebssystem prüfen, ob das Skript funktioniert. Kannst du mir denn eine funktionierende Lösung anbieten, welche generisch funktioniert? Hast du mal geprüft, wo genau im Skript der Fehler steckt?

**Comment by mrpiggi** [comment]
Mit der Version v2.06 und der Nutzung von Open Sans ist eine manuelle Schriftinstallation überflüssig. Lediglich das Paket `opensans` muss durch die Distribution zur Verfügung gestellt werden, der Nutzer sollte dieses jedoch nicht manuell laden.
