### ISSUE TITLE
Übersetzung von BIBTEX @mastersthesis ändern

### ISSUE THREAD

**Issue by shiaky** [tud-cd/tudscr#26]
Hallo Falk,

ich weiß, das hat absolut nichts mit der TUDSCR Vorlage zu tun, aber vielleicht kannst du mit deinem enormen Latex-Wissen trotzdem weiter helfen. Da sicher auch andere das Problem haben, schreibe ich es hier als Issue.

Ich habe in meiner Bib Datei einen Eintrag: 
```
@mastersthesis{zau10,
    author     =     {Max Muster},
    title     =     {{Some Title}},
    school     =     {TU Dresden},
    address     =     {Germany},
    year     =     {2042},
    }
```
Wenn ich das Literaturverzeichnis ausgeben lasse, generiert es mir darauf den Eintrag
```
Max Muster. »ISome Title«. Magisterarb. Germany: TU Dresden, 2042.
```

Was mich daran stört ist das Wort `Magisterarb.` Kennst du einen Weg, wie ich dort ein Wort wie `Masterarb.` hinzaubern kann?

Minimalbeispiel:
```latex
\RequirePackage[ngerman=ngerman-x-latest]{hyphsubst}
\documentclass[english,ngerman,BCOR=6mm,cdgeometry=no,DIV=13,abstract=notoc]{tudscrreprt}
\usepackage{selinput}\SelectInputMappings{adieresis={ä},germandbls={ß}}
\usepackage[T1]{fontenc}
%%% Zitation
\usepackage[babel,german=guillemets]{csquotes}
\usepackage[
backend=biber,
style=alphabetic,
sorting=nyt
]{biblatex}
\addbibresource{literatur.bib}
\begin{document}
\printbibliography[heading=bibintoc]
\end{document}
```
mit oben aufgeführtem Eintrag in der `literatur.bib`.

**Comment by mrpiggi** [comment]
Hi,
> ich weiß, das hat absolut nichts mit der TUDSCR Vorlage zu tun, aber ... da sicher auch andere das Problem haben, schreibe ich es hier als Issue.
Da hast du wohl den Verwendungszweck von Issues nicht ganz verstanden. Diese sollten in erster Linie genutzt werden, um Bugs zu berichten oder eventuell auch nicht existierende Funktionen anzufragen. Auf alle Fälle sollte zu einem speziellen Projekt hier nichts nachgefragt werden, was absolut nichts damit zu tun hat. Was glaubst du denn, wie viel Leute mit einem ähnlichen Problem genau **hier** vorbeischauen?

Dafür gibt es Foren, sowohl eine spezielles für die Anwendung von TUD-Script (https://latex.wcms-file3.tu-dresden.de/phpBB3/index.php) als auch allerlei für LaTeX im Allgemeinen (bspw. http://www.golatex.de/).

Des weiteren wäre ein kompilierbares Minimalbeispiel (`literatur.bib` liegt lokal bei dir) wünschenswert sowie ein kurzer Blick in die Anleitung von [`biblatex`](https://www.ctan.org/pkg/biblatex) ratsam. Wenn man dort nach dem Eintragstyp `mastersthesis` sucht, findet man folgenden Absatz:
> Similar to @thesis except that the type field is optional and defaults to the
localised term ‘Master’s thesis’. You may still use the type field to override that. 

[Man kann das natürlich noch generischer machen, indem man den entsprechend String für das Feld `type` anpasst bzw. definiert](http://lmgtfy.com/?q=biblatex+string+masterarbeit).

Beide Lösungen:
```latex
\RequirePackage[ngerman=ngerman-x-latest]{hyphsubst}
\documentclass[english,ngerman,BCOR=6mm,cdgeometry=no,DIV=13,abstract=notoc]{tudscrreprt}
\usepackage[T1]{fontenc}
\usepackage{selinput}\SelectInputMappings{adieresis={ä},germandbls={ß}}
\begin{filecontents}{\jobname-temp.bib}
@thesis{Muster42,
  author  = {Max Muster},
  title   = {{Some Title}},
  school  = {TU Dresden},
  address = {Germany},
  year    = {2042},
  type    = {Masterarb.}
}
@thesis{Muster43,
  author  = {Max Muster},
  title   = {{Some Title}},
  school  = {TU Dresden},
  address = {Germany},
  year    = {2043},
  type    = {masterthesis}
}
\end{filecontents}
%%% Zitation
\usepackage{babel}
\usepackage[babel,german=guillemets]{csquotes}
\usepackage[
  backend=biber,
  style=alphabetic,
  sorting=nyt
]{biblatex}
\addbibresource{\jobname-temp.bib}
\NewBibliographyString{masterthesis}%
\DefineBibliographyStrings{ngerman}{%
  masterthesis = {Masterarbeit}
}
\begin{document}
\cite{Muster42, Muster43}
\printbibliography[heading=bibintoc]
\end{document}
```
Grüße
Falk

**Comment by shiaky** [comment]
Vielen Vielen Dank dir Falk :D 

Das Forum wäre natürlich geeigneter gewesen als der Issuetracker.  Danke dir für den Hinweiß.

Ich denke, die Leute, die diese Vorlage kennen, schauen bei allen Problemen  die sie haben durchaus erst einmal hier in die Issues rein. 

Tex und Latex sind mit persönlich so schleierhaft und unverständlich, dass ich nie einschätzen kann, ob mein Problem jetzt an der Konfiguration von tudscr liegt oder ob ich einfach eine Doku eines Paketes nicht ausführlich gelesen habe. Das kannst du natürlich besser einschätzen und fragst dich dann, wie so dumme Fragen hier in den Issuetracker kommen.

Danke dir nochmals :D

**Comment by mrpiggi** [comment]
> Tex und Latex sind mit persönlich so schleierhaft und unverständlich, dass ich nie einschätzen kann, ob mein Problem jetzt an der Konfiguration von `tudscr` liegt oder ob ich einfach eine Doku eines Paketes nicht ausführlich gelesen habe.

Das lässt sich relativ schnell überprüfen, indem du einfach ein Minimalbeispiel erstellst und dann die Dokumentklasse von `tudscrreprt` auf `report` oder zumindest `scrreprt` änderst. Taucht das Problem dennoch auf, liegt es nicht an TUD-Script.
