### ISSUE TITLE
\supervisorname verursacht fehlerhafte Titelseite bei \subject{student}

### ISSUE THREAD

**Issue by rotton** [tud-cd/tudscr#27]
Sobald man im kommenden MWE `\supervisorname` einbindet, erscheint eine 0.Seite (vor der eigentlichen Titelseite) mit dem Namen des Betreuers in Serifenschrift. Auf der eigentlichen Titelseite erscheint er jedoch nicht. Woran liegt das?

```
\documentclass[12pt, a4paper, cdgeometry=true, twoside=false, titlepage=on]{tudscrreprt}
\TUDoption{cdfont}{false, nodin, serifmath}

\usepackage[ngerman]{babel}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenx}

\usepackage{mathptmx}
\usepackage[scaled=.92]{helvet}
\usepackage{courier}

\begin{document}

\subject{student}
\title{Das wird mal meine supertolle Studienarbeit in \LaTeX{} mit dem an der TUD üblichen viel zu langen Titel}
\subtitle{Einführung ins Maschinenwesen}
\faculty{Fakultät Maschinenwesen}
\institute{Institut für \TeX nische Logistik}
\author{Miriam Mustermann}
\matriculationnumber{1234567}
%\supervisorname{Prof. Dr.-Ing. Martin Müller}
\date{23.12.2023}

\pagenumbering{gobble}
\maketitle

\end{document}

```

**Comment by mrpiggi** [comment]
Der Befehl `\supervisorname` ist ein sprachabhängiger Bezeichner, der für Deutsch als aktive Sprache die Bezeichnung _Betreuer_ enthält und liest auch kein Argument. Du solltest stattdessen den Befehl `\supervisor{...}` verwenden. Steht auch alles so in der Dokumentation.
