### ISSUE TITLE
OpenSans has been selected to replace Univers

### ISSUE THREAD

**Issue by max-leuthaeuser** [tud-cd/tudscr#28]
OpenSans has been selected to replace Univers.
Will there be an update here to have OpenSans available throughout all templates?

**Comment by mrpiggi** [comment]
I'll try my best to provide support for OpenSans starting in February 2018

**Comment by mattisebastian** [comment]
I'd love to have that feature as well.

**Comment by benkuly** [comment]
Me too.

**Comment by keinstein** [comment]
Some preliminary work has been done in tud-cd/tud-cd/tex/latex/beamerfontthemetud.sty for presentations. I have tested it with LuaLaTeX so far. But I didn't care much about math fonts. That means I used the first math font that provides everything that is needet to get results.

**Comment by mrpiggi** [comment]
As for Univers I already did some coding in order to use as much from OpenSans for math fonts, but I'm not finished yet. In future, it should be enough to only load package `tudscrfonts` and OpenSans can be used in math mode.

**Comment by mattisebastian** [comment]
Is there any progress on this? :)

**Comment by mrpiggi** [comment]
Unfortunately not yet

**Comment by mrpiggi** [comment]
This should work
```tex
\documentclass[ngerman,cdfont=false,cdfont=nodin]{tudscrreprt}
\usepackage[T1]{fontenc}
\usepackage{selinput}
\SelectInputMappings{adieresis={ä},germandbls={ß}}
\usepackage[default]{opensans}
\usepackage{babel}
\usepackage[math]{blindtext}
\begin{document}
\blinddocument
\end{document}
```

**Comment by mattisebastian** [comment]
Thank you, that worked really well. I still had an old version using \documentclass{tudbook}.

**Comment by mrpiggi** [comment]
The support for Open Sans is not implemented yet in the tudscr bundle and the opensans package does not support the fontspec package. But I'm currently working on it and hopefully I'm able to prepare a new release till the end of next week.

**Comment by keinstein** [comment]
Actually it is the other way round: FontSpec supports Open Sans if it is installed in your GUI system. You can use the official font files. In tud-beamerstyle I use the following code for LuaLaTeX:

    \usepackage{fontspec}
    \setmainfont{TeX Gyre Pagella}
    \RequirePackage{unicode-math}
      \setmathfont{XITS Math}
      \setmainfont{Open Sans}
      \setsansfont{Open Sans}
      \setmathfont[range={up}]{Open Sans}
      \setmathfont[range={it}]{Open Sans Italic}
      \setmathfont[range={bfup}]{Open Sans Bold}
      \setmathfont[range={bfit}]{Open Sans Bold Italic}
      \setmathfont[range={sfup}]{Open Sans Condensed Light}
      \setmathfont[range={sfit}]{Open Sans Condensed Light Italic}
      \setmathfont[range={bfsfup}]{Open Sans Light}
      \setmathfont[range={bfsfit}]{Open Sans Light Italic}
      \setmathfont[range=\mathfrak]{STIXGeneral}

This gives you limited Maths support.

**Comment by baloe** [comment]
@mrpiggi 
the snippet you gave works but it doesn't affect the fonts used in the tile page.
Any idea on how to have fonts used in the title page replaced by opensans?
```
\documentclass[ngerman,cdfont=false,cdfont=nodin]{tudscrreprt}
\usepackage[T1]{fontenc}
\usepackage{selinput}
\SelectInputMappings{adieresis={ä},germandbls={ß}}
\usepackage[default]{opensans}
\usepackage{babel}
\usepackage[math]{blindtext}
\begin{document}

\faculty{Juristische Fakultät}
\department{Fachrichtung Strafrecht}
\institute{Institut für Kriminologie}
\chair{Lehrstuhl für Kriminalprognose}
\date{18.02.2015}
\author{Mickey Mouse}
\title{Der Geldspeicher in Entenhausen}
\maketitle
\blinddocument

\end{document}
```

**Comment by baloe** [comment]
okay, I figured it out: 
In the following MWE the TUD header entries are modified in such a  way that they are typeset with Opensans. One can thus layout a desired titlepage from scratch and still profit from the header elements defined in the tudscr-packages.
I think I will use this MWE as a basis for a latex class to be distributed to our students.

```
\documentclass[ngerman,cdfont=false,cdfont=nodin]{tudscrreprt}
\usepackage[T1]{fontenc}
\usepackage{selinput}
\SelectInputMappings{adieresis={ä},germandbls={ß}}
\usepackage{babel}
\usepackage[math]{blindtext}

\usepackage[default, scale=0.8]{opensans}
\DeclareRobustCommand\ebseries{\fontseries{eb}\selectfont}
\DeclareRobustCommand\nbseries{\fontseries{b}\selectfont}
\DeclareRobustCommand\sbseries{\fontseries{sb}\selectfont}
\DeclareRobustCommand\rgseries{\fontseries{m}\selectfont}
\DeclareRobustCommand\ltseries{\fontseries{l}\selectfont}
\DeclareRobustCommand\clseries{\fontseries{cl}\selectfont}
\DeclareTextFontCommand{\texteb}{\ebseries}
\DeclareTextFontCommand{\textsb}{\sbseries}
\DeclareTextFontCommand{\textlt}{\ltseries}
\DeclareTextFontCommand{\textcl}{\clseries}


\begin{document}

\faculty{{\fosfamily\nbseries Juristische Fakultät}}
\department{{\fosfamily\rgseries Fachrichtung Strafrecht}}
\institute{{\fosfamily\rgseries Institut für Kriminologie}}
\chair{{\fosfamily\rgseries Lehrstuhl für Kriminalprognose}}

\pagestyle{empty.tudheadings}

Individuell gestaltete Titelseite

\cleardoublepage
\pagestyle{scrheadings}

\blinddocument

\end{document}
```

**Comment by j-stephan** [comment]
Any news on this?

**Comment by j-stephan** [comment]
@mrpiggi Which steps would be required to replace Univers / DIN with OpenSans in the templates themselves? I've seen the workarounds here but I'm more interested in the "out of the box" experience. Do you need any help? Could you list the files that would need to be changed?

**Comment by fl4m** [comment]
The `default` option of the **opensans** package just changes the font used in the main text body. To change the font used in the headings, include the `defaultsans` option as well:

```latex
\usepackage[default, defaultsans]{opensans}
```

**Comment by baloe** [comment]
> The `default` option of the **opensans** package just changes the font used in the main text body. To change the font used in the headings include the `defaultsans` option as well:
> 
> ```
> \usepackage[default, defaultsans]{opensans}
> ```

I don't see why that should be necessary, the opensans docs read

> You can set LATEX to use Open Sans as standard font throughout the whole
document by passing the default option to the package:
`\usepackage[default]{opensans}`
To set Open Sans as default sans-serif only:
`\usepackage[defaultsans]{opensans}`

My understanding is that with `default` one should not need `defaultsans`.

`defaultsans` has indeed no effect in the MWE which I posted on July 28th;
even without `defaultsans`, headings are typeset in opensans which is good, but Univers is still being used in the header and on the title page.

You won't be able to reproduce this behavior without Univers installed, by the way.
