### ISSUE TITLE
How to update the new tudscr in the local distribution folder?

### ISSUE THREAD

**Issue by XiaodiJin** [tud-cd/tudscr#31]
I used miktex as the distribution, and the windows as the plattform. When there are some updates of **_tudscr_**, how could I update the local file of the miktex?
I should download the whole repository **_tudscr_**,  and then should I copy the folder **_tudscr/source_** from the repository into my local path **_D:\MiTek2.9\source_** ?
This is not a difficult question, but I did not find the manual to teach me how to do it. Can somebody help me? Thanks a lot!!

**Comment by mrpiggi** [comment]
Just use the update function of MiKTeX
