### ISSUE TITLE
Referenzen in \caption{} lassen pdflatex nicht mehr terminieren

### ISSUE THREAD

**Issue by florianblume** [tud-cd/tudscr#32]
Wird das caption package eingebunden und werden in einer caption z.B. Sektionen referenziert so läuft pdflatex unendlich lange und terminiert nicht mehr.

Verhindert werden kann das, wenn zuerst alles ohne captions compiliert wird und dann ein zweites Mal mit, das ist aber umständlich.

Minimally working example:

\documentclass[color]{tudscrreprt}
\usepackage{caption}

\begin{document}

\section{test}\label{sec:one}

\begin{figure}
    \caption{\ref{sec:one}}
\end{figure}

\end{document}

**Comment by mrpiggi** [comment]
Danke für das Melden des Problems. Ich werde es mit der v2.06 beheben. Hoffentlich habe ich diese bis Ende nächste Woche *endlich* fertig...
