### ISSUE TITLE
tudscr... incompatible with sansmath

### ISSUE THREAD

**Issue by baloe** [tud-cd/tudscr#33]
The following MWE works fine: Opensans is used for both - text and math. 
```
\documentclass[10pt,a4paper]{scrartcl}
\usepackage[utf8]{inputenc}
\usepackage[default, scale=0.85]{opensans}
\usepackage{sansmath}   % math-font matching text sans font
\sansmath               % actually tell tex to use it!
\begin{document}
	foo  1 $1 = f$
\end{document}
```

When instead using the tudscrartcl class, an odd combination of serif numbers and opensans letters is used in math mode: 
```
\documentclass[10pt,a4paper, cdfont=false]{tudscrartcl}
\usepackage[utf8]{inputenc}
\usepackage[default, scale=0.85]{opensans}
\usepackage{sansmath}   % math-font matching text sans font
\sansmath               % actually tell tex to use it!
\begin{document}
	foo  1 $1 = f$
\end{document}
```

**Comment by mrpiggi** [comment]
Well, unfortunately I'm really busy and can not provide a quick fix for this issue. Hopefully I'll find some time during the holidays on Christmas to finish the integration of the Open Sans fonts to the bundle. Sorry.

**Comment by sisyga** [comment]
The following works for me to get math font as sans serif, symbols are unchanged though. You also don't need to scale the text.

~~~Latex
\documentclass[10pt,a4paper, cdfont=false]{tudscrartcl}
\usepackage[utf8]{inputenc}
\usepackage[default]{opensans}
\usepackage[italic, LGRgreek]{mathastext}
\begin{document}
	foo  1 $1 = f$
\end{document}

**Comment by mrpiggi** [comment]
With version v2.06 Open Sans is supported. Whether `mathastext` nor `opensans` should be loaded manually since this version.
