### ISSUE TITLE
Wrong vertical spacing when using \thispagestyle{tudscrheadings}.

### ISSUE THREAD

**Issue by sisyga** [tud-cd/tudscr#34]
Using the tudscr document classes I can make use of the tudscr page styles. However, when using `\thispagestyle{tudscrheadings}`, the vertical spacing does not work properly and the text and tud heading overlap. Using `\pagestyle{tudscrheadings}` works correctly, but is obviously not the correct choice, when I want exactly one page to be of this style.

Background: I want to use the tudscrartcl class, without the CD title page, which uses up a huge amount of space. To workaround that, I want to use the tudscrheadings page style only on the first page.
Heres a MWE to reproduce the issue:

~~~latex
\documentclass{tudscrartcl}
\usepackage{blindtext}
\begin{document}
\thispagestyle{tudscrheadings}
\blindtext
\end{document}

**Comment by mrpiggi** [comment]
This is a very messy behavior but sadly not easy to change since the selection of a tudheadings page style requires a adaption of the type area. Nevertheless, you can use the `tudpage` environment:
```tex
\documentclass{tudscrartcl}
\usepackage{blindtext}
\begin{document}
\blindtext
\begin{tudpage}
\blindtext
\end{tudpage}
\blindtext
\end{document}
```

**Comment by sisyga** [comment]
This way I get a single page in the tud style, but it is only practical if I know the length of the content associated with the page. However, I need a solution, where only the very first page is of this style, independent of the content. Otherwise it becomes messy, when adding/removing stuff from inside the tudpage environment. My sub-optimal workaround for now uses `\vspace*{1.5cm}`:
~~~latex
\documentclass{tudscrartcl}
\usepackage{blindtext}
\begin{document}
\thispagestyle{tudscrheadings}\vspace*{1.5cm}
\blinddocument
\end{document}
~~~
Are there any major drawbacks to this approach?

**Comment by mrpiggi** [comment]
> Are there any major drawbacks to this approach?

No, at least I can not think of any upcoming issues right now.
