### ISSUE TITLE
\confirmation mit Umlaut im \author

### ISSUE THREAD

**Issue by ax3l** [tud-cd/tudscr#37]
Hallo,

ich schreibe ein Dokument der Klasse `tudscrreprt` mit Hauptsprache englisch.

Beim Erstellen der `\confirmation` verschluckt sich mein Umlaut `ü` im Nachnamen zu `Axel H\IeC {\"u}bl` im PDF und kann auch nicht mit `\author{Axel H\"ubl}` leicht gefixt werden (wird dann ohne Umschreibung als `Axel H\"ubl`) übernommen.

Wie kann ich das Problem lösen? An allen anderen Stellen klappt mein Umlaut, z.B. auf dem Deckblatt.

Versionen:
- 2016/10/12 v2.05f TUD-Script
- scrlfile, 2016/06/14 v3.21 KOMA-Script package

**Comment by mrpiggi** [comment]
Das funktioniert bei mir problemlos:
```latex
\documentclass{tudscrreprt}
\usepackage[T1]{fontenc}

\begin{document}
\title{Testtitel}
\author{Axel Hübel}
\confirmation
\end{document}
```
Document Class: tudscrreprt 2017/05/30 v2.05m TUD-Script document class (scrreprt)
Document Class: scrreprt 2019/02/01 v3.26b KOMA-Script document class (report)

**Comment by ax3l** [comment]
Komisch, klappt bei mir nicht:
![main](https://user-images.githubusercontent.com/1353258/55225865-ed43a380-5213-11e9-92af-54540be3d683.png)

```bash
echo $LANG
# en_US.utf8
echo $LC_CTYPE 
# de_DE.UTF-8
echo $LC_MESSAGES                                     
# en_US.UTF-8
```

Document Class: tudscrreprt 2016/10/12 v2.05f TUD-Script document class (scrreprt)
Document Class: scrreprt 2016/06/14 v3.21 KOMA-Script document class (report)

**Comment by mrpiggi** [comment]
Dann aktualisiere bitte mal deine Distribution, aktuell sind
`tudscrreprt 2017/05/30 v2.05m`
`scrreprt 2019/02/01 v3.26b`
