### ISSUE TITLE
Minus symbol ("-") not working in math mode, showing "{" (open curly bracket) instead

### ISSUE THREAD

**Issue by sisyga** [tud-cd/tudscr#40]
Hey,
thanks for updating the project and changing the default font to open sans. However I noticed a bug: The minus symbol ("-") is not shown correctly in math mode, it shows a curly bracket instead. Here's a MWE:
~~~latex
\documentclass{tudscrartcl}
\begin{document}
	 1 - f; $1 - f$
\end{document}
~~~

**Comment by mrpiggi** [comment]
Hey,
at least with T1-encoding everything works as expected. But with OT1-encoding as well as with `fontspec` there is an issued indeed. Unfortunately, I can not work on it until next week.
```tex
\documentclass{tudscrartcl}
\ifpdftex{
  \usepackage[T1]{fontenc}
%  \usepackage[OT1]{fontenc}
}{
  \usepackage{fontspec}
}
\begin{document}
	 1 - f; $1 - f$
\end{document}
```
