### ISSUE TITLE
Sigma symbol gets replaced with final sigma

### ISSUE THREAD

**Issue by sasanjac** [tud-cd/tudscr#42]
Whenever using `\sigma` σ not followed by another greek symbol it gets converted to a final sigma (`\varsigma` ς) instead.

**Comment by mrpiggi** [comment]
So I tried a couple of different setups and I assume, that you are using LuaLaTeX as the following MWE shows the problem, if this engine is used. With pdfLaTeX as well as XeLaTeX everything works as expected. Am I right?
```tex
\documentclass{tudscrartcl}
\ifpdftex{
  \usepackage[T1]{fontenc}
}{
  \usepackage{fontspec}
}
\begin{document}
$\alpha\sigma$

$\sigma + \varsigma + \sigma\varsigma$
\end{document}
```

**Comment by sasanjac** [comment]
Yes, sorry I forgot to mention that Im using LuaLateX. For now I can't get XeLateX to compile so I can't verify it working.
