### ISSUE TITLE
Package scrbase Warning: Usage of deprecated command `\ifstr'

### ISSUE THREAD

**Issue by sisyga** [tud-cd/tudscr#49]
Hi there,
this is a minor thing, as everything is still compiling. But when I use tudscr in Overleaf, I get tons of these warnings:

> Package scrbase Warning: Usage of deprecated command `\ifnumber'.
> (scrbase)                The command has been renamed because of a
> (scrbase)                recommendation of The LaTeX Project Team.
> (scrbase)                Please replace `\ifnumber' by `\Ifnumber' on input lin
> e 447.

and

> Package scrbase Warning: Usage of deprecated command `\ifstr'.
> (scrbase)                The command has been renamed because of a
> (scrbase)                recommendation of The LaTeX Project Team.
> (scrbase)                Please replace `\ifstr' by `\Ifstr' on input line 561.

As I said, it still compiles, but it is just annyoing to get 20+ of these warnings in an almost empty document. Hope this can be as easily fixed as it seems.

Best,

Simon

**Comment by sisyga** [comment]
I've just seen that overleaf still has v2.06e. So maybe this was solved already in the current version, and we just have to wait for overleaf to update?

**Comment by mrpiggi** [comment]
Exactly. Do you use Overleaf via ZIH? Then this is what you are looking for: https://tex.zih.tu-dresden.de/read/pjksfgrxdzgj

**Comment by sisyga** [comment]
Great, thank you!
