### ISSUE TITLE
Space in header on chapter pages

### ISSUE THREAD

**Issue by gutzbenj** [tud-cd/tudscr#50]
Dear Falk,

thanks for your work on the scripts. I'm completely new to LaTeX and have just started a new document. I was wondering if the whitespace in the header for example for pages like 

\listoffigures
\listoftables

and normal chapters like

\chapter{Chapter1}

is planned or if it could be reduced. I guess that for the normal chapters one doesn't need to include the typical header of TU Dresden but instead simply mention the chapter or something similar.

Thanks for your help!

**Comment by mrpiggi** [comment]
Do you mean the vertical white space before a chapter title? If so, see options `pageheadingsvskip` and `headingsvskip`.

**Comment by gutzbenj** [comment]
Exactly this space. Or does it ajust at some point, let's say when my list of figures starts filling?

**Comment by mrpiggi** [comment]
Nope, this space is fixed as it was recommended some years ago by the corporate design. Switching to Open Sans as main font two years ago, [a new manual was released](https://tu-dresden.de/intern/services-und-hilfe/kommunizieren-und-publizieren/cd), but this is a complete mess. For example, there are four different styles for headings. This is nothing I am going to implement. So, if you want to reduce the amount of the vertical space in front of a chapter, just use option `headingsvskip` with a negative length.
