### ISSUE TITLE
"genehmigte Dissertation" auf Deckblatt?

### ISSUE THREAD

**Issue by steven-omaha** [tud-cd/tudscr#53]
Welche Möglichkeit gibt es in `tudscr`, eine genehmigte Dissertation von der eingereichten Dissertation abzugrenzen? Im Normalfall wird auf das Deckblatt statt "Dissertation" dann "genehmigte Dissertation" geschrieben. In der Anleitung habe ich nichts entsprechendes gefunden.

**Comment by mrpiggi** [comment]
Im einfachsten Fall verwendest du einfach

    \thesis{Genehmigte Dissertation}

**Comment by steven-omaha** [comment]
Das war ja einfach. Mir war nicht bewusst, dass das eine Option ist. Danke!
