### ISSUE TITLE
Datum bei \confirmation leer lassen

### ISSUE THREAD

**Issue by knightshrub** [tud-cd/tudscr#55]
Hallo,

was ist denn die einfachste Möglichkeit bei der Selbstständigkeitserklärung das Datum frei zu lassen, sodass ich es händisch nachtragen kann? Dies ist z.B. dann hilfreich wenn ich vor dem offiziellen Abgabedatum abgeben möchte.

Wenn ich vor `\confirmation*` einfach `\date{}` benutze, spuckt latex auch nicht mehr den Ort aus.

**Comment by knightshrub** [comment]
Okay, habe es dann doch mit der Doku und einem Blick in  `tudscrreprt.cls` rausgefunden.

`\confirmationclosing{\medskip\noindent\getfield{place}, den\vskip8ex\noindent\getfield{author}}`

**Comment by mrpiggi** [comment]
Solltest du das Paket `isodate` _nicht_ verwenden, ginge auch einfach `\date{\relax}`. Ich habe mir das als ToDo notiert.
