### ISSUE TITLE
SIunitx version 3 doesnt display greek letters as units

### ISSUE THREAD

**Issue by Pratched** [tud-cd/tudscr#64]
Hello. While using texlive on debian with cat-version 2.06l of tudscr Ive encountered a problem with the unit \ohm within siunitx.

```latex
\documentclass{tudscrbook}
\usepackage{siunitx}
\begin{document}
	\si{\ohm}
\end{document}
```
Returns a `W` instead of an omega. Changing the document class to `scrbook` yields the correct unit. I presume it has something to do with font support and there might be a workaround, but setting something like `\sisetup{text-ohm=\Omega}` or `\DeclareSIunit{..}` has not worked for me so far.

**Comment by Pratched** [comment]
Well I seem to have upgraded shortly after siunitx version 3 has been published (9th of Jun 2021) and I can confirm this issue only appears in use with version 3. `\usepackage{siunitx}[=v2]` could be a nice workaround, if I havnt started to adopt some new features right away.

**Comment by mrpiggi** [comment]
depending on the (maybe) upcoming discussion at https://github.com/josephwright/siunitx/issues/435#issuecomment-880229452 I will try to figure out an appropriate bug fix
