### ISSUE TITLE
Bricht mit texlive 2015.38835

### ISSUE THREAD

**Issue by devkid** [tud-cd/tudscr#7]
Folgendes Minimalbeispiel bricht seit texlive 2015.38835:
```latex
\documentclass{tudscrreprt}
\begin{document}
\chapter{Test}
\end{document}
```

Mit:
```
chapter 1.
! Argument of InputIfFileExists has an extra }.
<inserted text> 
                par 
l.3 \chapter{Test}
                  
?
```

Kompiliert mit:
`latexmk test.tex`

**Comment by tudscr** [comment]
Ohne Log-File ist eine fundierte Aussage schwierig, vermutlich sollte Tex Live aktualisiert werden. Dieses Minimalbeispiel
```
\documentclass[cdfont=false]{tudscrreprt}
\begin{document}
\KOMAScriptVersion

\TUDVersion
\end{document}
```
sollte die folgende Ausgabe
```
2015/10/03 v3.19a KOMA-Script
2015/10/06 v2.04b TUD-KOMA-Script
```
erzeugen.

**Comment by tudscr** [comment]
@devkid Hat ein Update geholfen? Dann würde ich bitten, das Ticket zu schließen.

**Comment by devkid** [comment]
@tudscr Der vorherige Fehler ist jetzt weg, dafür kann man jetzt keine Optionen für `geometry` mehr angeben:

```latex
\documentclass{tudscrreprt}
\usepackage[scale=0.8]{geometry}
\begin{document}
\chapter{Test}
\end{document}
```

Fehler:
```
! LaTeX Error: Option clash for package geometry.
```

Lokal installiert ist jetzt `texlive-tudscr 2.04c`.

**Comment by tudscr** [comment]
Eins vorneweg: Sauber wäre es das Ticket mit deinem letzten Problem – im Idealfall auch ohne Nachfrage meinerseits – zu schließen und für das jetzige Problem ein neues Ticket zu öffnen. So und jetzt zum eigentlichen Problem:


Die Fehlermeldung erscheint schlichtweg und ergreifend, weil die TUD-KOMA-Script-Klassen das Paket `geometry` von sich aus laden. Du kannst das Problem – wie bei sämtlichen Optionskonflikten – umgehen, indem du **vor** dem Laden der Klasse deine gewünschten Optionen mit `\PassOptionsToPackage{scale=0.8}{geometry}`  an das Paket durchreichst. Einen Hinweis zu der Fehlermeldung findest du auch im Handbuch zu TUD-KOMA-Script

Allerdings hatten und haben Optionen für `geometry` ohne weitere Maßnahmen keinerlei Einfluss auf den Satzspiegel, weder in der aktuellen Version noch in den Versionen zuvor. Vergleich mal die Ergebnisse der Ausgabe mit und ohne der ersten Zeile
```latex
%\PassOptionsToPackage{scale=0.8}{geometry}
\documentclass[cdgeometry=false]{tudscrreprt}
\usepackage{showframe}
\begin{document}
\chapter{Test}
\end{document}
```
Falls du unbedingt den Satzspiegel ändern willst, dann solltest du das Paket `geometry` laden, deine gewünschten Einstellungen speichern und diese zu Beginn des Dokumentes wiederherstellen.
```latex
\documentclass[cdgeometry=false]{tudscrreprt}
\usepackage{geometry}
\geometry{scale=0.8}
\savegeometry{test}

\usepackage{showframe}
\begin{document}
%\loadgeometry{test}
\chapter{Test}
\end{document}

```

**Comment by devkid** [comment]
Tatsache, war mir gar nicht aufgefallen, dass die Optionen für `geometry` gar keine Wirkung hatten.

In `texlive-tudscr 2.03` und dem alten `texlive` konnte ich allerdings `\usepackage{geometry}` verwenden – hier wurde es offensichtlich noch nicht von der TUD-KOMA-Script-Klasse geladen?!

**Comment by tudscr** [comment]
Bis zur Version v2.03 wurde das Laden des Paketes bis an das Ende der Präambel verzögert, um genau solche Optionskonflikte zu vermeiden. Dies führte jedoch zu einigen unschönen Konstrukten im Quelltext. Da die Optionen ohnehin keinen Einfluss hatten, wird es jetzt direkt geladen.
