### ISSUE TITLE
Unrecognized command \RedeclareSectionCommand

### ISSUE THREAD

**Issue by sebk26** [tud-cd/tudscr#79]
What I want to do: *Reduce space above chapter title*
What works with `scrbook` and `scrreprt` and not with `tudscrbook` and `tudscrreprt`:
```latex
\RedeclareSectionCommand[
afterindent=false,
beforeskip=0pt,
afterskip=2\baselineskip]{chapter}
```
I read that the above command works for KOMA 3.17a and greater.

**Is there a dependency to an older KOMA version or do I need to load some additional packages?**

**Comment by sebk26** [comment]
Updated texlive 2021 to texlive 2022 and are now stuck at error reported in #78
Will update this issue after Hotfix.

**Comment by mrpiggi** [comment]
As the intention of this bundle is to provide an uniform layout, there is no purpose to provide a versatile interface for customization. Nevertheless, have a look at options `headingsvskip` and maybe `pageheadingsvskip`

**Comment by sebk26** [comment]
Thank's @mrpiggi ,

i will go with 
```latex
\TUDoptions{headingsvskip=-100pt}
\TUDoptions{pageheadingsvskip=30pt}
```
for now.
Apparently `headingsvskip` affects titlepage and chapterpage and i need `pageheadingsvskip` to correct the `titlepage` as I only want the chapter to move further to the pagetop.

I'm happy for other suggestions as this feels like it's not intentional.

**Comment by mrpiggi** [comment]
Setting `headingsvskip` effects `pageheadingsvskip` as well if the latter is unset. So `pageheadingsvskip=0pt` should let title, parts and chapterpages in the same place as the default settings.
