### ISSUE TITLE
Erweiterte Mathematische Symbole

### ISSUE THREAD

**Issue by fehrlich** [tud-cd/tudscr#8]
Ich habe gerade auf die neue version des tu scriptes geupdatet.
wenn man das Packet MnSymbol läd, kommt es zu in der aktuellen Version zu komischen Ausgaben. 
Ich habe das Testdokument um ein mimimalbeispiel erweitert.

```
\RequirePackage[ngerman=ngerman-x-latest]{hyphsubst}
\documentclass[english,ngerman]{tudscrman}
\usepackage{selinput}\SelectInputMappings{adieresis={ä},germandbls={ß}}
\usepackage[T1]{fontenc}
\lstset{%
  inputencoding=utf8,extendedchars=true,
  literate=%
    {ä}{{\"a}}1 {ö}{{\"o}}1 {ü}{{\"u}}1
    {Ä}{{\"A}}1 {Ö}{{\"O}}1 {Ü}{{\"U}}1
    {~}{{\textasciitilde}}1 {ß}{{\ss}}1
}

\usepackage{amsmath} %math
\usepackage{MnSymbol}% symbols
\usepackage{syntax}

\begin{document}

\begin{equation}
\tag{Test}
  f( x ) \less B \text{ keine Klammern fx statt f(x)}
  \label{eqn:T-New}
\end{equation}

\begin{grammar}
<Program> ::= <Entity>* <Expression>
\end{grammar}

\end{document}
```

Wenn man MnSymbol ausklammert funktioniert das Beispiel ansonsten bekommt man folgenden output:

![bug](https://cloud.githubusercontent.com/assets/7313884/11452760/ea9eb9a2-95f2-11e5-8908-1ee7000d51f7.PNG)

In der vorherigen Version (welche is ausversehen gelöscht habe) wurde alles richtig angezeigt.

**Comment by tudscr** [comment]
Das Problem ist, das MnSymbol nun nicht dafür gedacht ist, zusammen mit den Univers-Schriften im Mathematikmodus zu funktionieren. Leider ist das mit den Schriften für den Mathematiksatz alles andere als einfach zu gestalten und aus meiner Sicht schlichtweg unmöglich mit allen verfügbaren Paketen zu koordinieren.

Du kannst entweder als Klassenoption cdmath=false setzen oder aber auf MnSymbol verzichten. Ich sehe zumindest bei deinem Beispiel auch keine Notwendigkeit für das Paket. Alle früheren Versionen von TUD-KOMA-Script findest du unter https://github.com/tud-cd/tudscr/releases

**Comment by fehrlich** [comment]
Danke für die schnelle Antwort.

Ich brauch verschiedene Symbole wie \nprec für meine Arbeit, habe diese jetzt allerdings mit Überlagerung von Symbolen nachgebaut, was erstmal funktioniert.

Mir wurde gesagt das ich diese Klasse tudscrman verwenden soll (für meine Diplomarbeit), aber ich werde mich damit nochmal an meinen Betreuer richten.

**Comment by tudscr** [comment]
Es ist tatsächlich sehr schwierig, dir da konkret weiterzuhelfen. Das Problem ist schlichtweg: Es gibt für die CD-Schriften keine adäquaten Schriften für den Mathematiksatz. Ist für eine Technische Universität ja aber auch nicht beachtenswert, wenn man sich für ein CD entscheidet ;) Im einfachsten Fall nutzt du TUD-KOMA-Script und setzt einfach die Option `cdfont=false` und lässt den ganzen Zauber mit den Univers-Schriften einfach weg.

Die TUD-KOMA-Script-Klassen für Anwender sind `tudscrartcl`, `tudscrreprt` und `tudscrbook`.

**Comment by fehrlich** [comment]
:smile: das werde ich bei dem nächsten Problem mit der Schrift mit Sicherheit tun. Danke
