### ISSUE TITLE
Package geometry Error: \loadgeometry: name `' undefined in texlive 2022.1

### ISSUE THREAD

**Issue by sisyga** [tud-cd/tudscr#80]
Seit dem Update auf Texlive 2022.1 werfen die tudscr-Klassen o.g. Fehler raus. In 2021.1 funktionierte noch alles.
log-file befindet sich im Anhang.

MWE:

```
\documentclass{tudscrbook}

\title{test}
\author{ }
\date{August 2022}

\begin{document}

\maketitle

\section{Introduction}

\end{document}
```
[output.log](https://github.com/tud-cd/tudscr/files/9416211/output.log)

**Comment by sisyga** [comment]
I use sharelatex/Overleaf from TU Dresden, so I cannot manually update any packages.

**Comment by mrpiggi** [comment]
Well, then get the latest version from CTAN and put it into your project path.
