### ISSUE TITLE
binding correction (BCOR) only applied to the left

### ISSUE THREAD

**Issue by s9105947** [tud-cd/tudscr#87]
Dear Maintainer,

when using the option `cdgeometry=asymmetric` for a double-page layout, and setting a binding correction with `BCOR`, the binding correction is only applied to the left side.

## Steps to Reproduce
Create a document using the following options:

```
\documentclass[cdgeometry=asymmetric,BCOR=3mm,twoside,openright]{tudscrreprt}
```

## Expected Behavior
The binding correction (`BCOR=3mm`) is applied to the **inner** side,
i.e. pages on the left (even) have extra space on the right,
pages on the right (odd) have extra space on the left.

## Actual Behavior
The binding correction is **always** applied to the **left** side,
i.e. to the inner side for pages on the right,
and to the outer side for pages on the left.

## Further Notes
I tested `BCOR=3mm`, but any value seems to work.

I have not checked which combinations of other parameters affect this.

I could not find any related issues online,
i.e. this seems to be a tudscr-specific problem (instead of applying to all of KOMA).

I can prepare a minimal document or can carry out further testing if required.
I'm not sure how to solve this, but if you give me some hints I can try to prepare a PR.

**Comment by mrpiggi** [comment]
Hi,

this isn't true. Just set a very huge value for `BCOR` like this:

```
\documentclass[cdgeometry=asymmetric,BCOR=50mm,twoside,openright]{tudscrreprt}
\usepackage{blindtext}
\begin{document}
\Blinddocument
\end{document}
```

As mentioned in the manual, the combination of `twoside` with `cdgeometry=asymmetric` is all but optimal as the latter setting forces the asymmetric layout with a greater **left** (not _inner_) margin disregarding page number being odd or even.

This said, you could easily go with `cdgeometry=symmetric/centred` or see, if `cdgeometry=twoside/balanced` fits your needs.

**Comment by s9105947** [comment]
Hi,

thanks for the follow up.
I mistook `asymmetric` as "another setup for `twopage`", which it is not (as I see now).
Hence my confusion.

Thanks again.
